import uuid
from flask import Flask, request, jsonify
from flask_limiter import Limiter
from flask_limiter.util import get_remote_address
from signals import get_llm_confidence_score, get_stylometric_score
from logger import write_log, get_logs, update_log_for_appeal

app = Flask(__name__)

# Initialize Rate Limiter
limiter = Limiter(
    get_remote_address,
    app=app,
    default_limits=[],
    storage_uri="memory://"
)

@app.route('/submit', methods=['POST'])
@limiter.limit("10 per minute;100 per day")
def submit_content():
    data = request.get_json()
    
    if not data or 'text' not in data or 'creator_id' not in data:
        return jsonify({"error": "Missing 'text' or 'creator_id'"}), 400
        
    text = data['text']
    creator_id = data['creator_id']
    content_id = str(uuid.uuid4())
    
    # 1. Fire both signals
    llm_score = get_llm_confidence_score(text)
    stylo_score = get_stylometric_score(text)
    
    # 2. Calculate weighted confidence (60% LLM, 40% Stylometrics)
    confidence = (llm_score * 0.6) + (stylo_score * 0.4)
    confidence = round(confidence, 2)
    
    # 3. Apply thresholds and actual UI Labels
    if confidence >= 0.75:
        attribution = "likely_ai"
        label = "Text generated by AI. This content exhibits strong semantic and structural patterns consistent with artificial generation."
    elif confidence >= 0.36:
        attribution = "uncertain"
        label = "Uncertain Origin. This content exhibits mixed structural and semantic traits common to both human and AI writing."
    else:
        attribution = "likely_human"
        label = "Human-written content. This text demonstrates natural variability and stylistic coherence typical of human authorship."
        
    # 4. Construct the Audit Log Entry
    log_entry = {
        "content_id": content_id,
        "creator_id": creator_id,
        "attribution": attribution,
        "confidence": confidence,
        "llm_score": llm_score,
        "stylo_score": stylo_score,
        "status": "classified"
    }
    
    write_log(log_entry)
    
    return jsonify({
        "content_id": content_id,
        "attribution": attribution,
        "confidence": confidence,
        "label": label
    }), 200

@app.route('/appeal', methods=['POST'])
def appeal_content():
    """Endpoint for creators to contest a classification."""
    data = request.get_json()
    
    if not data or 'content_id' not in data or 'creator_reasoning' not in data:
        return jsonify({"error": "Missing 'content_id' or 'creator_reasoning'"}), 400
        
    content_id = data['content_id']
    reasoning = data['creator_reasoning']
    
    update_log_for_appeal(content_id, reasoning)
    
    return jsonify({
        "status": "success",
        "message": "Appeal logged and status updated to under review."
    }), 200

@app.route('/log', methods=['GET'])
def view_logs():
    """Returns the structured audit log as JSON."""
    return jsonify({"entries": get_logs()}), 200

if __name__ == '__main__':
    app.run(debug=True, port=5000)