import os
import json
import re
import statistics
from unittest import result
from groq import Groq
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

client = Groq(api_key=os.environ.get("GROQ_API_KEY"))

def get_llm_confidence_score(text: str) -> float:
    """
    Signal 1: LLM-Based Classification using openai/gpt-oss-120b.
    Returns a float between 0.0 (Highly likely human) and 1.0 (Highly likely AI).
    """
    try:
        response = client.chat.completions.create(
            model="openai/gpt-oss-120b",
            messages=[
                {
                    "role": "system",
                    "content": (
                        "You are an AI detection system. Analyze the following text "
                        "and determine the likelihood that it was generated by an AI. "
                        "Respond ONLY with a JSON object containing a single key 'ai_confidence_score' "
                        "with a float value between 0.0 (Highly likely human) and 1.0 (Highly likely AI). "
                        "Do not include any markdown formatting or explanations."
                    )
                },
                {
                    "role": "user",
                    "content": text
                }
            ],
            temperature=0.0,
            response_format={"type": "json_object"}
        )
        
        content = response.choices[0].message.content
        if not content:
            return 0.5

        result = json.loads(content)
        return float(result.get("ai_confidence_score", 0.5))
    
    except Exception as e:
        print(f"Error calling Groq API: {e}")
        return 0.5

def get_stylometric_score(text: str) -> float:
    """
    Signal 2: Stylometric Heuristics.
    Measures sentence length variance and vocabulary diversity (type-token ratio).
    Returns a float between 0.0 (Highly variable/Human) and 1.0 (Highly uniform/AI).
    """
    # 1. Calculate Sentence Length Variance
    sentences = [s.strip() for s in re.split(r'[.!?]+', text) if s.strip()]
    
    if len(sentences) < 2:
        variance_score = 0.5  # Not enough data for variance
    else:
        lengths = [len(s.split()) for s in sentences]
        variance = statistics.variance(lengths)
        # Higher variance is more human. We invert it so high variance = low AI score.
        # Assuming a variance of 40+ is very human.
        variance_score = max(0.0, 1.0 - (variance / 40.0))

    # 2. Calculate Type-Token Ratio (Vocabulary Diversity)
    words = [w.lower() for w in re.findall(r'\b\w+\b', text)]
    if not words:
        ttr_score = 0.5
    else:
        ttr = len(set(words)) / len(words)
        # Higher TTR means more diverse vocabulary (more human).
        ttr_score = max(0.0, 1.0 - ttr)

    # Combine both stylometric metrics into a single score
    final_stylo_score = (variance_score + ttr_score) / 2.0
    return round(final_stylo_score, 2)